// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpticEMS.Data.Database.Context;

#nullable disable

namespace OpticEMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430164833_RecipeImplementation")]
    partial class RecipeImplementation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OpticEMS.Contracts.Services.Database.SpectralLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ionization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Wavelength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Wavelength");

                    b.ToTable("SpectralLines");
                });

            modelBuilder.Entity("OpticEMS.Contracts.Services.Recipe.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutocalibrationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionWindowHighs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectionWindowTime")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ExposureMs")
                        .HasColumnType("REAL");

                    b.Property<int>("InitialDelay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxEndpointTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverEtchEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverEtchValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PcaComponents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PcaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PcaMinTrainingSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScansNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StableThresholdPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WavelengthColors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wavelengths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WindowInCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowOutCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
