// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpticEMS.Data.Database.Context;

#nullable disable

namespace OpticEMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OpticEMS.Contracts.Services.Database.SpectralLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ionization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Wavelength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Wavelength");

                    b.ToTable("SpectralLines");
                });
#pragma warning restore 612, 618
        }
    }
}
